figure:
  color: "green"
  legend_loc: "lower left"
  title: "frequency character"
  figsize: [7.2, 4.8]

  xlabel: "frequency[Hz]"
  xscale: "log"
  xticks: [[1000, 10000, 100000, 1000000, 10000000], ["1k", "10k", "100k", "1M", "10M"]]

  axes:
    amp:
      ylabel: "amplitude[dB]"
      style: "solid"
      yscale: "linear"

    phase:
      ylabel: "phase[deg]"
      style: "dashed"
      yscale: "linear"
